### ISSUE TITLE
Question about lintdiff

### ISSUE THREAD

**Issue by exussum12** [plume-lib/plume-scripts#1]
Hi!

I have come across the note in your repo here
https://github.com/plume-lib/plume-scripts/blob/cb538cd26b0d8d101cf7e81ea866df32259b01e1/lint-diff.py#L35

Have you got an example where this is not the case ? I would love to try and resolve that. Ive used it successfully with pylint

**Comment by mernst** [comment]
Thanks for asking.  I'm glad to hear it works with pylint.  I recall multiple serious issues for my use case (with output of javac, javadoc, and linters).

If there had been just a few issues, I would have reported them.  But given my experience, I didn't report them or retain the tests.  Sorry about that.  For reference, it looks like this was around July 2018.

**Comment by exussum12** [comment]
Ok thanks. I dont use java myself currently but will give it a test and check it out. I've not touched the java stuff since then probably but as long as the format hasn't changed it shouldn't matter. 

If you do come across an instance which doesn't work feel free to report it and I will look into it

**Comment by mernst** [comment]
@exussum12 I will let you know if I notice a problem.
